export const mockUser = {
  id: '1',
  username: 'JDM_Ryusei',
  location: 'Los Angeles, CA',
  profilePhoto: null,
  car: {
    year: 2002,
    make: 'Nissan',
    model: 'Silvia S15',
    photo: null,
    hp: 247,
    torque: 203,
    mods: [
      'HKS GT2835 Turbo',
      'Nismo Suspension Kit',
      'Bride Zeta III Seats',
      'Cusco Roll Cage',
      'Work Emotion CR Kiwami Wheels',
      'Tomei Exhaust',
    ],
    zeroToSixty: '4.8s',
    drivetrain: 'RWD',
    engine: 'SR20DET Turbocharged',
  },
  stats: {
    meetsAttended: 47,
    meetsHosted: 8,
    friends: 234,
    rating: 4.8,
  },
  rank: 'Unranked',
  cardStyle: {
    background: 'original',
    outlineColor: '#FF0080',
    aura: 'none',
  },
};

export const mockMeets = [
  {
    id: '1',
    title: 'SoCal JDM Night',
    location: 'Santa Monica Pier Parking Lot',
    date: 'Friday, Apr 18 · 8:00 PM',
    carTypes: ['JDM', 'Import', 'Tuner'],
    rsvps: 147,
    hostedBy: 'SpeedKingLA',
    description:
      'Monthly JDM meet at the pier. All imports welcome. Keep it clean — no revving in residential areas on the way out.',
  },
  {
    id: '2',
    title: 'Sunday Stance Session',
    location: 'Irwindale Speedway',
    date: 'Sunday, Apr 20 · 10:00 AM',
    carTypes: ['Stance', 'Fitment', 'All Makes'],
    rsvps: 89,
    hostedBy: 'StancedOut_LA',
    description: 'Show off your setup. Best fitment wins bragging rights.',
  },
  {
    id: '3',
    title: 'Euro Night LA',
    location: 'Downtown Los Angeles',
    date: 'Saturday, Apr 26 · 9:00 PM',
    carTypes: ['European', 'German', 'Italian'],
    rsvps: 63,
    hostedBy: 'BavarianKing_',
    description: "First Euro-focused meet of the year. BBS wheels encouraged.",
  },
  {
    id: '4',
    title: 'Drift Practice Day',
    location: 'Willow Springs Raceway',
    date: 'Saturday, May 3 · 7:00 AM',
    carTypes: ['Drift', 'RWD', 'Track'],
    rsvps: 34,
    hostedBy: 'DriftKingZero',
    description: 'Open drift practice. All skill levels welcome. Helmets required.',
  },
];

export const mockUsers = [
  {
    id: '2',
    username: 'TurboQueen_ATL',
    location: 'Atlanta, GA',
    car: { year: 2018, make: 'Subaru', model: 'WRX STI' },
    stats: { meetsAttended: 31, meetsHosted: 3, friends: 189, rating: 4.6 },
    rank: 'Unranked',
  },
  {
    id: '3',
    username: 'V8_Phantom',
    location: 'Houston, TX',
    car: { year: 2020, make: 'Ford', model: 'Mustang GT500' },
    stats: { meetsAttended: 52, meetsHosted: 11, friends: 312, rating: 4.9 },
    rank: 'Unranked',
  },
  {
    id: '4',
    username: 'KanjiDrift',
    location: 'San Francisco, CA',
    car: { year: 1999, make: 'Toyota', model: 'Supra MK4' },
    stats: { meetsAttended: 88, meetsHosted: 22, friends: 501, rating: 4.7 },
    rank: 'Unranked',
  },
  {
    id: '5',
    username: 'NeonRacer_MIA',
    location: 'Miami, FL',
    car: { year: 2021, make: 'Honda', model: 'Civic Type R' },
    stats: { meetsAttended: 19, meetsHosted: 1, friends: 98, rating: 4.5 },
    rank: 'Unranked',
  },
  {
    id: '6',
    username: 'SleeperS14',
    location: 'Phoenix, AZ',
    car: { year: 1997, make: 'Nissan', model: '240SX S14' },
    stats: { meetsAttended: 66, meetsHosted: 14, friends: 278, rating: 4.8 },
    rank: 'Unranked',
  },
  {
    id: '7',
    username: 'AWD_Beast',
    location: 'Denver, CO',
    car: { year: 2015, make: 'Mitsubishi', model: 'Lancer Evo X' },
    stats: { meetsAttended: 43, meetsHosted: 7, friends: 167, rating: 4.6 },
    rank: 'Unranked',
  },
];
